site_name: Agents Concierge Tech Guides
site_url: ''
repo_name: Agents Concierge
repo_url: https://github.com/cvn-computergross/agents-concierge
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
theme:
  name: material
  features:
  - content.code.copy
nav:
- Home: index.md
- Agent Builder:
  - Lista Agenti: lv1/index.md
  - Tech Support (v1):
    - Panoramica: lv1/tech-support/index.md
    - Setup Guide: lv1/tech-support/lab-guide.md
  - Job Writer (v1):
    - Panoramica: lv1/job-writer/index.md
    - Setup Guide: lv1/job-writer/lab-guide.md
  - Postman (v1):
    - Panoramica: lv1/postman/index.md
    - Setup Guide: lv1/postman/lab-guide.md
  - Talent Scout (v1): 
    - Panoramica: lv1/talent-scout/index.md
    - Setup Guide: lv1/talent-scout/lab-guide.md

- Copilot Studio:
  - Lista Agenti: lv2/index.md
  - Tech Support (v2):
    - Panoramica: lv2/tech-support/index.md
    - Setup Guide: lv2/tech-support/lab-guide.md
  - Job Writer (v2):
    - Panoramica: lv2/job-writer/index.md
    - Setup Guide: lv2/job-writer/lab-guide.md
  - Postman (v2):
    - Panoramica: lv2/postman/index.md
    - Setup Guide: lv2/postman/lab-guide.md
  - Talent Scout (v2): 
    - Panoramica: lv2/talent-scout/index.md
    - Setup Guide: lv2/talent-scout/lab-guide.md