site_name: Agents Concierge Tech Guides
site_url: ''

repo_name: 'Agents Concierge'
repo_url: 'https://github.com/cvn-computergross/agents-concierge'

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
theme:
  name: material
  features:
  - content.code.copy
nav:
- Home: index.md
- Agent Builder:
  - Overview: lv1/index.md
  - Tech Support: lv1/tech-support/index.md
  - Template Writer: lv1/job-writer/index.md
- Copilot Studio:
  - Overview: lv2/index.md
  - Tech Support: lv2/tech-support/index.md
  - Template Writer: lv2/job-writer/index.md