site_name: Agents Concierge Tech Guides
site_url: ''
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
theme:
  name: material
  features:
  - content.code.copy
nav:
- Home: index.md
- Agent Builder:
  - Overview: lv1/index.md
  - IT Help Desk: lv1/it-help-desk/index.md
  - HR Assistant: lv1/hr-assistant/index.md
  - Tech Support: lv1/tech-support/index.md
  - Template Writer: lv1/template-writer-/index.md
- Copilot Studio:
  - Overview: lv2/index.md
  - IT Help Desk: lv2/it-help-desk/index.md
  - HR Assistant: lv2/hr-assistant/index.md
  - Tech Support: lv2/tech-support/index.md
