site_name: "Agents Concierge Tech Guides"
site_url: ""

markdown_extensions:
  - admonition
  - pymdownx.details

theme:
  name: material

nav:
  - Home: index.md
  - Agent Builder:
      - Overview: lv1/index.md
      - IT Help Desk: lv1/it-help-desk/index.md
      - HR Assistant: lv1/hr-assistant/index.md
  - Copilot Studio:
      - Overview: lv2/index.md
      - IT Help Desk: lv2/it-help-desk/index.md
      - HR Assistant: lv2/hr-assistant/index.md